pipeline {
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage("checkout scm"){
            steps {
                checkout scm
            }
        }
        stage("sonarcloud-analysis"){
            steps{
                withSonarQubeEnv ('sonarqube'){
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Hossnia_geo1'
            }
            }
            
        }
        stage("maven-build"){
            steps{
                sh 'mvn clean; mvn validate; mvn compile; mvn install; mvn package; mvn test'
            }
        }

        stage("upload artifact"){
            sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd \
            -T target/bio*.jar \
            "http://ec2-52-91-124-244.compute-1.amazonaws.com:8081/artifactory/geolocation/bio_$BUILD_TAG"'
        }
    }
}